// constants/permissions
export const PERMISSIONS = {
  // User Management
  ADD_USER: 1,
  EDIT_USER: 2,
  DELETE_USER: 3,
  VIEW_USERS: 29,

  // Customer Management
  ADD_CUSTOMER: 4,
  EDIT_CUSTOMER: 5,
  DELETE_CUSTOMER: 6,
  VIEW_CUSTOMERS: 25,

  // Role Management
  ADD_ROLE: 7,
  EDIT_ROLE: 8,
  DELETE_ROLE: 9,
  VIEW_ROLE: 48,
  VIEW_USER_ROLES: 31,

  // Store Management
  ADD_STORE: 10,
  EDIT_STORE: 11,
  DELETE_STORE: 12,
  VIEW_STORE: 49,

  // Order Management
  ADD_ORDER: 13,
  EDIT_ORDER: 14,
  DELETE_ORDER: 15,
  SHOW_PAYMENTS_HISTORY: 16,
  SHOW_ORDER_HISTORY: 17,
  VIEW_ORDERS: 19,
  VIEW_ORDER: 50,
  VIEW_ORDERSTATUS_HISTORY: 51,
  VIEW_ORDER_PAYMENTS: 52,

  // Payments Management
  VIEW_PAYMENTS: 21,
  ADD_PAYMENTS: 57,
  EDIT_PAYMENTS: 58,

  // Service Management
  VIEW_SERVICES: 23,

  // Reports Management
  VIEW_REPORTS: 27,
  GENERATE_REPORTS: 28,

  // Production Management
  VIEW_PRODUCTION: 33,

  // Task Management
  VIEW_TASKS: 53,
  
  // Feedback Management
  VIEW_FEEDBACKS: 55,

  //PROJEC TYPES Management
  VIEW_PROJECTTYPE:61,
  ADD_PROJECTYPE:62,
  EDIT_PROJECTYPE:63,
  DELETE_PROJECTTYPE:64,

//Reference Management
    VEIW_REFERENCES:69,
    ADD_REFERENCES:66,
    EDIT_REFERENCES:67,
    DELETE_REFERENCES:68,
  
  // Menu Management
  ACCESS_DASHBOARD: 37,
  ACCESS_ORDERS: 38,
  ACCESS_PAYMENTS: 39,
  ACCESS_SERVICES: 40,
  ACCESS_CUSTOMERS: 41,
  ACCESS_REPORTS: 42,
  ACCESS_USERS: 43,
  ACCESS_USERROLES: 44,
  ACCESS_PRODUCTION: 45,
  ACCESS_STORES: 46,
  ACCESS_PROJECTTYPES:59,
  ACCESS_FEEDBACKS: 56,
  ACCESS_TASKS: 54,
  ACCESS_REFERENCES:60,
};
